hashmain: hashmain.cc htable.cc entry.h hashmain.h htable.h 
	g++ -std=c++14 -Wall -Werror -Wextra -pedantic -g -o hashmain hashmain.cc htable.cc

clean:
	rm -f hashmain

world: clean hashmain
